---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-staging
  template:
    metadata:
      labels:
        app: python-app-staging
    spec:
      containers:
      - name: python-app
        image: cmtrieu/flask-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
