---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service-staging
spec:
  type: NodePort
  selector:
    app: python-app-staging
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
