---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-prod
  template:
    metadata:
      labels:
        app: python-app-prod
    spec:
      containers:
      - name: python-app
        image: cmtrieu/flask-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
